In [2]:
import numpy as np

# DataTypes and Attributes 

In [4]:
#Numpy's main datatype in ndarry
#Vector
#1-Dimension Shape(1,3)
a1 = np.array([1,2,3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
# 2-Dimension Matrix Shape(2,3)
a2 = np.array([[1,2,3],
             [4,5,6]])



In [11]:
type(a2)

numpy.ndarray

In [8]:
# N Dimension
#Shape (2,3,3)

a3 = np.array([[ [1,2,3],
                [4,5,6],
                [6,7,8]],
              [[4,4,4],
              [5,6,6],
              [7,7,7]]
    
])

In [10]:
type(a3)

numpy.ndarray

In [13]:
a1.shape

(3,)

In [14]:
a2.shape

(2, 3)

In [15]:
a3.shape

(2, 3, 3)

In [16]:
a1.ndim, a2.ndim, a3.ndim #Dimension

(1, 2, 3)

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [21]:
#Create datafram from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [4]:
## Creating NUmpy Array. 
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [9]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
ones.dtype

dtype('float64')

In [12]:
type(ones)

numpy.ndarray

In [14]:
zeros = np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
range_array = np.arange(0, 10, 2)

In [16]:
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[0, 1, 5, 6, 8],
       [0, 3, 1, 8, 5],
       [2, 5, 6, 1, 7]])

In [25]:
random_array.size, random_array.shape

(15, (3, 5))

In [26]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.47769501, 0.37802384, 0.65818928],
       [0.51535149, 0.3500565 , 0.72935134],
       [0.35756434, 0.09972198, 0.95469828],
       [0.08894887, 0.71439673, 0.76874444],
       [0.13629015, 0.33203824, 0.21747299]])

In [27]:
random_array_3 = np.random.rand(5,3)

In [28]:
random_array_3

array([[0.86696688, 0.16806632, 0.28684276],
       [0.1783495 , 0.74517244, 0.75811044],
       [0.52219167, 0.60989223, 0.71689573],
       [0.22229119, 0.67569318, 0.28465405],
       [0.93184605, 0.33243778, 0.88872969]])

In [56]:
#Pseudo Random Numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size = (5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [64]:
#Pseudo Random Numbers
np.random.seed(seed = 0)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])